// This Activity handles user authentication (Login/Registration).
// It observes the AuthViewModel for changes in authentication state.

package com.stempediatask.mvvmappdemo.view;

import android.os.Bundle;
import androidx.appcompat.app.AppCompatActivity;
import androidx.lifecycle.ViewModelProvider;
import android.content.Intent;
import android.view.View;
import android.widget.Toast;

import com.stempediatask.mvvmappdemo.databinding.ActivityAuthBinding; // Generated by View Binding
import com.stempediatask.mvvmappdemo.viewmodel.AuthViewModel;

public class AuthActivity extends AppCompatActivity {

    private ActivityAuthBinding binding; // View Binding instance
    private AuthViewModel authViewModel;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        binding = ActivityAuthBinding.inflate(getLayoutInflater());
        setContentView(binding.getRoot());

        // Initialize AuthViewModel
        authViewModel = new ViewModelProvider(this).get(AuthViewModel.class);

        // --- Observe LiveData from ViewModel ---

        // Observe current user status: if logged in, navigate to MainActivity
        authViewModel.getUserLiveData().observe(this, firebaseUser -> {
            if (firebaseUser != null) {
                // User is logged in, navigate to main app content
                Toast.makeText(AuthActivity.this, "Welcome " + firebaseUser.getEmail(), Toast.LENGTH_SHORT).show();
                startActivity(new Intent(AuthActivity.this, MainActivity.class));
                finish(); // Finish AuthActivity so user can't go back to login
            }
        });

        // Observe error messages from authentication attempts
        authViewModel.getErrorLiveData().observe(this, errorMessage -> {
            if (errorMessage != null && !errorMessage.isEmpty()) {
                Toast.makeText(AuthActivity.this, "Error: " + errorMessage, Toast.LENGTH_LONG).show();
            }
        });

        // Observe loading state to show/hide ProgressBar
        authViewModel.getLoadingLiveData().observe(this, isLoading -> {
            binding.progressBar.setVisibility(isLoading ? View.VISIBLE : View.GONE);
            binding.buttonLogin.setEnabled(!isLoading);
        });

        // --- Set up UI Listeners ---
        binding.buttonLogin.setOnClickListener(v -> {
            String email = binding.editTextEmail.getText().toString().trim();
            String password = binding.editTextPassword.getText().toString().trim();
            if (!email.isEmpty() && !password.isEmpty()) {
                authViewModel.login(email, password);
            } else {
                Toast.makeText(AuthActivity.this, "Please enter email and password", Toast.LENGTH_SHORT).show();
            }
        });

        // If user is already logged in, directly navigate
        if (authViewModel.getCurrentUser() != null) {
            startActivity(new Intent(AuthActivity.this, MainActivity.class));
            finish();
        }
    }
}